Standblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('articles/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login", views.user_login, name='login'),
    path("logout", views.user_logout, name='logout'),
    path("register", views.user_register, name='register'),
    path("edit", views.user_edit, name='edit'),

]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('detail/<slug:slug>', views.article_detail, name='article_detail'),
    path('list', views.article_list, name='articles_list'),
    path('category/<int:pk>', views.category_detail, name="category_detail"),
    path('search/', views.search, name="search_articles"),
    path('contact_us/', views.contactus, name="contact_us"),
    path('like/<slug:slug>/<int:pk>', views.like, name="like"),
    # path('detail/<slug:slug>', views.ArticleDetailView.as_view(), name='article_detail'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان")
    created = models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="articles", verbose_name="نویسنده")
    category = models.ManyToManyField(Category, related_name="articles", verbose_name="دسته بندی")
    title = models.CharField(max_length=70, verbose_name="عنوان")
    body = models.TextField(verbose_name="متن بدنه")
    image = models.ImageField(upload_to='images/articles', blank=True, null=True, verbose_name="تصویر")
    created = models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در")
    updated = models.DateTimeField(auto_now=True, verbose_name="آپدیت")
    published = models.BooleanField(default=True, verbose_name="انتشار")
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title} - {self.body[:30]}"

    def show_img(self):
        if self.image:
            return format_html(f'<img src="{self.image.url}" width="50px" height="50px">')
        return format_html('<h3 style="color: blue" >تصویر ندارد</h3>')
    show_img.short_description = "تصویر"


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments", verbose_name="مقاله")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments", verbose_name="کاربر")
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name="replies")
    body = models.TextField(verbose_name="متن بدنه")
    created = models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده در")

    def __str__(self):
        return self.body[:30]

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان")
    text = models.TextField(verbose_name="متن بدنه")
    email = models.EmailField(verbose_name="ایمیل")
    age = models.IntegerField(default=0, verbose_name="سن")
    created = models.DateField(auto_now_add=True, null=True, verbose_name="ساخته شده در")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "پیام"
        verbose_name_plural = "پیام ها"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Likes", verbose_name="کاربر")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="likes", verbose_name="مقاله")

    def __str__(self):
        return f"{self.user.username} - {self.article.title}"

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"

blog/forms.py
from django import forms
from django.core.validators import ValidationError

from blog.models import Message


class ContactUSForm(forms.Form):
    YEARS = ['2000', '2001', '2002']
    COLORS = [
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('red', 'Red')
    ]
    name = forms.CharField(max_length=10)
    text = forms.CharField(max_length=15)
    birth_year = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))
    favorite_color = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=COLORS)

    def clean(self):
        name = self.cleaned_data.get('name')
        text = self.cleaned_data.get('text')

        if name == text:
            raise ValidationError('name and text are the same', code="name_text_same")


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'
        widgets = {
            "title": forms.TextInput(attrs={
                "class": 'form-control',
                "placeholder": 'Enter your title'
            }),
            "text": forms.Textarea(attrs={
                "class": 'form-control',
                "placeholder": 'Enter your message'
            }),
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView

from .models import Article, Category, Comment, Message, Like
from django.core.paginator import Paginator
from .forms import ContactUSForm, MessageForm


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)

    if request.method == 'POST':
        parent_id = request.POST.get('parent_id')
        body = request.POST.get('body')
        Comment.objects.create(body=body, article=article, user=request.user, parent_id=parent_id)

    return render(request, "blog/article_details.html", {'article': article})


def article_list(request):
    articles = Article.objects.all()
    page_number = request.GET.get("page")
    paginator = Paginator(articles, 2)
    object_list = paginator.get_page(page_number)
    return render(request, "blog/articles_list.html", {'articles': object_list})


def category_detail(request, pk=None):
    category = get_object_or_404(Category, id=pk)
    articles = category.articles.all()
    return render(request, "blog/articles_list.html", {'articles': articles})


def search(request):
    q = request.GET.get('q')
    articles = Article.objects.filter(title__icontains=q)
    page_number = request.GET.get("page")
    paginator = Paginator(articles, 2)
    object_list = paginator.get_page(page_number)
    return render(request, "blog/articles_list.html", {'articles': object_list})


def contactus(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = MessageForm()
    return render(request, "blog/contact_us.html", {'form': form})


def like(request, slug, pk):
    try:
        like = Like.objects.get(article__slug=slug, user_id=request.user.id)
        like.delete()
    except:
        Like.objects.create(article_id=pk, user_id=request.user.id)
    return redirect('blog:article_detail', slug)


class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.like.filter(article__slug=self.object.slug, user_id=self.request.user.id):
            context['is_liked'] = True
        else:
            context['is_liked'] = False
        return context

blog/templates/blog/article_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% block title %}
        {{ articles.title }}
    {% endblock %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->

    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Article Details</h4>
                            <h2>{{ article.title }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->



    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="{{ article.image.url }}" alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>Lifestyle</span>
                                        <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">{{ article.author.username }}</a></li>
                                            <li><a href="#">{{ article.created }}</a></li>
                                            <li><a href="#">15 Comments</a></li>
                                        </ul>
                                        <p>{{ article.body }}</p>

                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        {% if is_liked %}
                                                            <li><a href="{% url "blog:like" article.slug article.id %}"><i
                                                                    style="font-size: 20px"
                                                                    class="fa fa-heart"></i>{{ article.likes.all.count }}
                                                            </a></li>
                                                        {% else %}
                                                            <li><a href="{% url "blog:like" article.slug article.id %}"><i
                                                                    style="font-size: 20px"
                                                                    class="fa fa-heart-o"></i>{{ article.likes.all.count }}
                                                            </a></li>
                                                        {% endif %}

                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#"> Twitter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item comments">
                                    <div class="sidebar-heading">
                                        <h2>4 comments</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for comment in article.comments.all %}
                                                {% if comment.parent == None %}
                                                    <li>
                                                        <div class="author-thumb">
                                                            {% if comment.user.profile.image %}
                                                                <img height="70px" width="70px"
                                                                     src="{{ comment.user.profile.image.url }}"
                                                                     alt="">
                                                            {% else %}
                                                                <img height="70px" width="70px"
                                                                     src="{% static 'images/icons/profile.png' %} "
                                                                     alt="">
                                                            {% endif %}
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ comment.user.username }}<span>{{ comment.created }}</span>
                                                            </h4>
                                                            <p>{{ comment.body }}</p>
                                                            <button onclick="set_value({{ comment.id }})"
                                                                    class="btn btn-primary">Reply
                                                            </button>
                                                        </div>
                                                    </li>
                                                    {% for reply in comment.replies.all %}
                                                        <li class="replied">
                                                            <div class="author-thumb">
                                                                {% if reply.user.profile.image %}
                                                                    <img height="70px" width="70px"
                                                                         src="{{ reply.user.profile.image.url }}"
                                                                         alt="">
                                                                {% else %}
                                                                    <img height="70px" width="70px"
                                                                         src="{% static 'images/icons/profile.png' %} "
                                                                         alt="">
                                                                {% endif %}
                                                            </div>
                                                            <div class="right-content">
                                                                <h4>{{ reply.user.username }}<span>{{ reply.created }}</span>
                                                                </h4>
                                                                <p>{{ reply.body }}</p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="col-lg-12">
                                    <div class="sidebar-item submit-comment">
                                        <div class="sidebar-heading">
                                            <h2 id="comment">Your comment</h2>
                                        </div>
                                        <div class="content">
                                            <form id="comment" action="#" method="post">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <input type="hidden" id="parent_id" name="parent_id" value="">
                                                    <div class="col-lg-12">
                                                        <fieldset>
                            <textarea name="body" rows="6" id="body" placeholder="Type your comment"
                                      required=""></textarea>
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <button type="submit" id="form-submit" class="main-button">
                                                                Submit
                                                            </button>
                                                        </fieldset>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url "account:login" %}">
                                    <button class="btn btn-dark mb-2"> For Sending a Comment Please login</button>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include "includes/sidebar.html" %}
            </div>
        </div>
    </section>

    <script>
        function set_value(id) {
            document.getElementById('parent_id').value = id;
            window.location.href = "#comment"
        }

    </script>
{% endblock %}

blog/templates/blog/articles_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Recent Posts</h4>
                            <h2>Our Recent Blog Entries</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-content">
                        <div class="row">
                            <div class="col-lg-8">
                                <span>Stand Blog HTML5 Template</span>
                                <h4>Creative HTML Template For Bloggers!</h4>
                            </div>
                            <div class="col-lg-4">
                                <div class="main-button">
                                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download
                                        Now!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            {% for article in articles %}
                                <div class="col-lg-6">
                                    <div class="blog-post">
                                        <div class="blog-thumb">
                                            <img src="{{ article.image.url }}" alt="">
                                        </div>
                                        <div class="down-content">
                                            <span>{{ article.category.all.first }}</span>
                                            <a href="{% url 'blog:article_detail' article.slug %}"><h4>{{ article.title }}</h4></a>
                                            <ul class="post-info">
                                                <li><a href="#">{{ article.author.username }}</a></li>
                                                <li><a href="#">{{ article.created }}</a></li>
                                                <li><a href="#">12 Comments</a></li>
                                            </ul>
                                            <p>{{ article.body }}</p>
                                            <div class="post-options">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <ul class="post-tags">
                                                            <li><i class="fa fa-tags"></i></li>
                                                            <li><a href="#">Best Templates</a>,</li>
                                                            <li><a href="#">TemplateMo</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-lg-12">
                                {% if articles.has_other_pages %}
                                    <ul class="page-numbers">
                                        {% if articles.has_previous %}
                                            <li><a href="?page={{ articles.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-left"></i></a></li>
                                        {% endif %}
                                        {% for i in articles.paginator.page_range %}
                                            {% if articles.number == i %}
                                                <li class="active"><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if articles.has_next %}
                                            <li><a href="?page={{ articles.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-right"></i></a></li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% include "includes/sidebar.html" %}
            </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}contact us{% endblock %}
{% block content %}
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>contact us</h4>
                            <h2>let’s stay in touch!</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->


    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    {{ form }}

                                                </div>
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">Send
                                                            Message
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="sidebar-item contact-information">
                                    <div class="sidebar-heading">
                                        <h2>contact information</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            <li>
                                                <h5>090-484-8080</h5>
                                                <span>PHONE NUMBER</span>
                                            </li>
                                            <li>
                                                <h5>info@company.com</h5>
                                                <span>EMAIL ADDRESS</span>
                                            </li>
                                            <li>
                                                <h5>123 Aenean id posuere dui,
                                                    <br>Praesent laoreet 10660</h5>
                                                <span>STREET ADDRESS</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}